In [2]:
# Import numpy as np and see the version
import numpy as np
print(np.__version__)

1.16.5


In [3]:
# create a 1D array.
ex = np.arange(5)
print(ex)

[0 1 2 3 4]


In [6]:
# create a boolean array
ex_1 = np.ones((2,2),dtype=int)
print(ex_1)

[[1 1]
 [1 1]]


In [7]:
# extract items that satisfy a given condition from 1D array.
# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Desired output: [1 3 5 7 9]
# Solution
print(arr[arr % 2 == 1])

[1 3 5 7 9]


In [8]:
# To replace items that satisfy a condition with another value in numpy array.
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [10]:
# To replace items that satisfy a condition without affecting the original array.
# arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
# Reshape an array.
arr = np.arange(10)
print(arr.reshape(2, -1))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [13]:
# stack two arrays vertically.
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [14]:
# stack two arrays horizontally.
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.concatenate([a, b], axis=1))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [16]:
# generate custom sequences in numpy without hardcoding.
a = np.array([1,2,3])
print(np.r_[np.repeat(a, 3), np.tile(a, 3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
